services:  
  mongodb:  
    environment:  
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}  
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}  
  
  app:  
    environment:  
      MONGODB_URI: ${MONGODB_URI}  
      NODE_ENV: ${NODE_ENV}  
      PORT: ${PORT}  
  
  frontend:  
    environment:  
      REACT_APP_API_URL: ${REACT_APP_API_URL}